config/urls.py
# Django
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.contrib.auth import views
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

# Authentication views
from fpt.users.authentication import (
    PasswordResetConfirmViewCustom,
    PasswordResetCustomView,
)

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    # User management
    path("", include("fpt.users.urls", namespace="users")),
    path("", include("fpt.orders.urls", namespace="orders")),
    path("", include("fpt.products.urls", namespace="products")),
    path("password_reset/", PasswordResetCustomView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmViewCustom.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

fpt/orders/urls.py
"""Orers URLs."""

# Django
from django.urls import path

# Views
from fpt.orders.views.carts import CartUpdateView
from fpt.orders.views.checkout import CheckoutView

app_name = "orders"

urlpatterns = [
    path("carrito/", CartUpdateView.as_view(), name="cart_update"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
]

fpt/products/urls.py
"""Shop URLs."""

# Django
from django.urls import path

# Views
from fpt.products.views.landing import LandingView
from fpt.products.views.products import ProductListView, ProductDetailView


app_name = "products"
urlpatterns = [
    path(route="", view=LandingView.as_view(), name="landing_page"),
    path(
        route="producto/<str:slug_name>/",
        view=ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        route="categoria/<slug:category_slug>/",
        view=ProductListView.as_view(),
        name="product_list_by_category",
    ),
    path(
        route="categoria/<slug:category_slug>/<slug:subcategory_slug>/",
        view=ProductListView.as_view(),
        name="product_list_by_subcategory",
    ),
]

fpt/users/urls.py
"""User URLs."""

# Django
from django.urls import path

# views
from fpt.users.views.users import SignUpView, LoginView, LogoutView, ProfileView

app_name = "users"
urlpatterns = [
    path(route="signup", view=SignUpView.as_view(), name="signup"),
    path(route="login/", view=LoginView.as_view(), name="login"),
    path(route="logout/", view=LogoutView.as_view(), name="logout"),
    path(route="profile/", view=ProfileView.as_view(), name="profile"),
]

fpt/orders/models/countries.py
# Django

from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)
    code = models.CharField(max_length=10, unique=True)
    phone_prefix = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name


class Department(models.Model):
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, related_name="departments"
    )
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        unique_together = ("country", "name")

    def __str__(self):
        return f"{self.name} ({self.country.code})"

fpt/orders/forms/carts.py
# Django
from django import forms
from django.forms import modelformset_factory

# Models
from fpt.orders.models.carts import CartItem


class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ["id", "quantity", "subtotal"]

    def clean_quantity(self):
        quantity = self.cleaned_data["quantity"]
        product = self.instance.product
        size = self.instance.size
        product_by_size = product.stock_by_size.filter(size=size).first()
        stock_by_size = product_by_size.stock if product_by_size else 0
        if product_by_size and (stock_by_size <= 0):
            raise forms.ValidationError("La cantidad debe ser al menos 1.")
        if quantity > stock_by_size:
            raise forms.ValidationError(
                f"Solo hay {product.stock} unidades disponibles."
            )
        return quantity


CartItemFormSet = modelformset_factory(
    CartItem, form=CartItemForm, extra=0, can_delete=False
)

fpt/products/forms/products.py
# Django
from django import forms

# Models
from fpt.products.models import ProductComment


class ProductCommentForm(forms.ModelForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)

    class Meta:
        model = ProductComment
        fields = ["first_name", "last_name", "email", "comment", "rating"]

fpt/orders/api/views/cart.py
# Django
from django.db import transaction

# Rest framework
from rest_framework import viewsets, mixins
from rest_framework.permissions import AllowAny

# Models
from fpt.orders.models import Cart

# Serializers
from fpt.orders.api.serializers import CartItemSerializer, CartModelSerializer

# Utils
from fpt.orders.utils.carts import get_or_create_cart


class CartViewSet(
    mixins.DestroyModelMixin,
    viewsets.GenericViewSet,
):
    """Cart viewset."""

    serializer_class = CartModelSerializer
    permission_classes = [AllowAny]
    queryset = Cart.objects.all()


class CartItemViewSet(
    mixins.CreateModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    mixins.ListModelMixin,
    viewsets.GenericViewSet,
):
    serializer_class = CartItemSerializer
    permission_classes = [AllowAny]

    def initial(self, request, *args, **kwargs):
        super().initial(request, *args, **kwargs)
        self.cart = get_or_create_cart(request)

    def get_queryset(self):
        return self.cart.cart_item.select_related("product")

    def perform_create(self, serializer):
        with transaction.atomic():
            product = serializer.validated_data.get("product")
            quantity = serializer.validated_data.get("quantity", 1)
            price = (
                product.discounted_price if product.discounted_price else product.price
            )

            existing_item = (
                self.cart.cart_item.select_for_update().filter(product=product).first()
            )

            if existing_item:
                pass
            else:
                serializer.save(cart=self.cart, subtotal=price * quantity)

    def perform_update(self, serializer):
        serializer.save(cart=self.cart)

fpt/orders/views/carts.py
# Django
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.forms import modelformset_factory

# Forms
from fpt.orders.forms.carts import CartItemForm

# Models
from fpt.orders.models.carts import CartItem

# Utils
from fpt.utils.mixins import EnsureCartExistsMixin


class CartUpdateView(EnsureCartExistsMixin, FormView):
    template_name = "cart/cart_forms.html"
    form_class = CartItemForm
    success_url = reverse_lazy("products:landing_page")

    def get_formset(self, data=None):
        cart_items = getattr(self.request, "cart_items", CartItem.objects.none())
        CartItemFormSet = modelformset_factory(
            CartItem, form=CartItemForm, extra=0, can_delete=True
        )
        return CartItemFormSet(data=data, queryset=cart_items)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["formset"] = kwargs.get("formset") or self.get_formset()
        return context

    def get(self, request, *args, **kwargs):
        formset = self.get_formset()
        return self.render_to_response(self.get_context_data(formset=formset))

    def post(self, request, *args, **kwargs):
        formset = self.get_formset(data=request.POST)
        if formset.is_valid():
            formset.save()
            messages.success(request, "Carrito actualizado correctamente.")
            return redirect(self.get_success_url())
        else:
            messages.error(request, "Ocurrió u.")
            return self.render_to_response(self.get_context_data(formset=formset))

fpt/orders/views/checkout.py
import hashlib

# Django
from django.views.generic.edit import FormView
from django.conf import settings
from django.urls import reverse_lazy

# Forms
from fpt.orders.forms.checkout import CheckoutForm

# Models
from fpt.users.models import UserAddress, User
from fpt.orders.models import Order

# Utils
from fpt.utils.mixins import EnsureCartExistsMixin
from fpt.utils.utilities import generate_reference_payment


class CheckoutView(EnsureCartExistsMixin, FormView):
    """Checkout view"""

    form_class = CheckoutForm
    template_name = "shop/checkout.html"
    success_url = reverse_lazy("orders:checkout")

    def dispatch(self, request, *args, **kwargs):
        self.cart = getattr(self.request, "cart", None)
        self.user = self.request.user if self.request.user.is_authenticated else None

        self.order = None
        if self.cart and self.user:
            self.order = Order.objects.filter(
                user=self.user,
                cart=self.cart,
                status="PENDING",
            ).first()
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = (
            self.request.user if self.request.user.is_authenticated else None
        )
        return kwargs

    def form_valid(self, form):
        if self.user:
            # Usuario autenticado, actualizar sus datos
            self.user.first_name = form.cleaned_data["first_name"]
            self.user.last_name = form.cleaned_data["last_name"]
            self.user.email = form.cleaned_data["email"]
            self.user.phone_number = form.cleaned_data["phone_number"]
            self.user.save()

        else:
            email = form.cleaned_data["email"]
            phone = form.cleaned_data["phone_number"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]

            self.user, created = User.objects.get_or_create(
                email=email,
                defaults={
                    "first_name": first_name,
                    "last_name": last_name,
                    "phone_number": phone,
                    "username": email,
                    "is_client": form.cleaned_data["create_account"],
                },
            )
            if not created:
                self.user.first_name = first_name
                self.user.last_name = last_name
                self.user.phone_number = phone
                self.user.save()

        # User address
        address, _ = UserAddress.objects.get_or_create(user=self.user)
        for field in form.Meta.fields:
            setattr(address, field, form.cleaned_data[field])
        address.save()

        # Create order
        if not self.order:
            self.order, _ = Order.objects.get_or_create(
                user=self.user, cart=self.cart, address=address, total=self.cart.total()
            )
            # Update cart status
            self.cart.status = "CHECKED_OUT"
            self.cart.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Si ya se creó la orden en esta sesión
        if self.order:
            amount_in_cents = int(self.order.total * 100)
            if not self.order.wompi_transaction_id:
                reference = generate_reference_payment()
                self.order.wompi_transaction_id = reference
                self.order.save()
            else:
                reference = self.order.wompi_transaction_id
            signature_string = (
                f"{reference}{amount_in_cents}COP{settings.WOMPI_INTEGRITY_KEY}"
            )
            integrity_signature = hashlib.sha256(
                signature_string.encode("utf-8")
            ).hexdigest()
            phone_number = self.user.phone_number
            prefix, number = phone_number[:3], phone_number[3:]
            context.update(
                {
                    "order": self.order,
                    "wompi_public_key": settings.WOMPI_PUB_KEY,
                    "wompi_reference": reference,
                    "url_redirect": "https://6fe965baebbf.ngrok-free.app",
                    "wompi_amount": amount_in_cents,
                    "wompi_signature": integrity_signature,
                    "user_email": self.user.email,
                    "user_phone": number,
                    "user_full_name": self.user.get_full_name(),
                    "prefix": prefix,
                }
            )
        return context

fpt/orders/views/orders.py
# Create your views here.

fpt/products/views.py
# Create your views here.

fpt/products/views/landing.py
# Views
from django.views.generic import TemplateView
from django.db.models import Prefetch

# Models
from fpt.products.models import Product, ProductImage


class LandingView(TemplateView):
    """Landing view."""

    template_name = "shop/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.filter(is_available=True).prefetch_related(
            Prefetch(
                "images",
                queryset=ProductImage.objects.filter(is_principal=True),
                to_attr="principal_image",
            )
        )
        context["best_sellers"] = products.filter(best_seller=True)[:8]
        context["newcomers"] = products.filter(newcomers=True)[:8]
        context["accessories"] = products.filter(category__name="Accesorios")
        return context


# Create your views here.

fpt/users/api/views.py
# Rest framewrok
from rest_framework import status
from rest_framework.decorators import action
from rest_framework import mixins
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

# Permissions
from rest_framework.permissions import AllowAny

# Models
from fpt.users.models import User

# Serializers
from .serializers import UserSerializer
from fpt.users.api.serializers import TransactionSerializer


class UserViewSet(
    mixins.RetrieveModelMixin,
    mixins.ListModelMixin,
    mixins.UpdateModelMixin,
    GenericViewSet,
):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)


class TransactionViewSet(mixins.CreateModelMixin, GenericViewSet):
    """Receptor wompi transactions viewset."""

    serializer_class = TransactionSerializer
    permission_classes = [AllowAny]

    def create(self, request, *args, **kwargs):
        """Create Membership and return response to bank."""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        data = {"response": "Thanks wompi."}
        return Response(data, status=status.HTTP_200_OK)

fpt/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">

    <head>
        <title>Futsal para todos</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="author" content="ThemeZaa" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0" />
        <meta name="description"
            content="Elevate your online presence with Crafto - a modern, versatile, multipurpose Bootstrap 5 responsive HTML5, SCSS template using highly creative 48+ ready demos." />
        <!-- favicon icon -->
        <link rel="shortcut icon" href="#" />
        <link rel="apple-touch-icon" href="#" />
        <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" />
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
            integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />
        <!-- google fonts preconnect -->
        <link rel="preconnect" href="https://fonts.googleapis.com" crossorigin />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <!-- slider revolution CSS files -->
        <link rel="stylesheet"
            type="text/css"
            href="{% static 'css/revolution/settings.css' %}" />
        <link rel="stylesheet"
            type="text/css"
            href="{% static 'css/revolution/layers.css' %}" />
        <link rel="stylesheet"
            type="text/css"
            href="{% static 'css/revolution/navigation.css' %}" />
        <!-- style sheets and font icons  -->
        <link rel="stylesheet" href="{% static 'css/vendors.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/icon.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/style.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/responsive.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/decor-store.css' %}" />
    </head>

    <body
    class="main-bg main-bg-opac roundedui adminuiux-header-standard adminuiux-sidebar-standard theme-purple adminuiux-header-transparent adminuiux-sidebar-fill-theme bg-white scrollup"
    data-theme="theme-orange" data-sidebarfill="adminuiux-sidebar-fill-theme" data-bs-spy="scroll"
    data-bs-target="#list-example" data-bs-smooth-scroll="true" tabindex="0"
    data-sidebarlayout="adminuiux-sidebar-standard" data-headerlayout="adminuiux-header-standard"
    data-headerfill="adminuiux-header-transparent">
    <header class="adminuiux-header">
        <nav class="navbar navbar-expand-lg fixed-top">
        </nav>
    </header>

    {% block container %}

    {% endblock container %}

    <script src="{% static 'assets/js/fitness/fitness-auth.js' %}"></script>
    {% block js %}

    {% endblock js %}


    </body>

</html>

fpt/templates/users/login.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}Futsal para todos{% endblock %}
{% block content %}
<!-- start section logiin-->
<section>
    <div class="container">
        <div class="row g-0 justify-content-center">
            <div class="col-xl-4 col-lg-5 col-md-10 contact-form-style-04 md-mb-50px section-login" data-anime='{ "translateY": [0, 0], "opacity": [0,1], "duration": 600, "delay":100, "staggervalue": 150, "easing": "easeOutQuad" }'>
                <span class="fs-26 xs-fs-24 alt-font fw-600 text-dark-gray mb-20px d-block">Inicia sesión</span>
                <form method="post">
                    {% csrf_token %}
                    {% if form.errors %}
                        <p class="alert alert-danger">Parcer@, contraseña o usuario incorrecto</p>
                    {% endif %}
                    <label class="text-dark-gray mb-10px fw-500">{{form.email.label}}<span class="text-red">*</span></label>
                    <input class="mb-20px bg-very-light-gray form-control required" type="email" name="email" placeholder="Ingrese su email" />
                    <label class="text-dark-gray mb-10px fw-500">Contraseña<span class="text-red">*</span></label>
                    <input class="mb-20px bg-very-light-gray form-control required" type="password" name="password" placeholder="Ingrese su contraseña" />
                    <div class="position-relative terms-condition-box text-start d-flex align-items-center mb-20px">
                        <label>
                            <input type="checkbox" name="rememberme" id="rememberme" value="1" class="terms-condition check-box align-middle">
                            <span class="box fs-14">Recuerdame</span>
                        </label>
                        <a href="/password_reset" class="fs-14 text-dark-gray fw-500 text-decoration-line-bottom ms-auto">Olvidaste tu contraseña?</a>
                    </div>
                    <button class="btn btn-medium btn-round-edge btn-base-color btn-box-shadow w-100" type="submit">Iniciar sesión</button>
                </form>
                <div class="small text-secondary text-center mb-4">No tienes cuenta? <a href="/signup" class="fs-14 text-dark-gray fw-500 text-decoration-line-bottom ms-auto">Crea una gratuita</a></div>
            </div>
        </div>
    </div>
</section>
<!-- end section -->
{% endblock %}

fpt/templates/users/register.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}Futsal para todos{% endblock %}
{% block content %}
<!-- start section logiin-->
<section>
    <div class="container">
        <div class="row g-0 justify-content-center">
            <div class="col-xl-6 col-lg-6 col-md-10 section-login" data-anime='{ "translateY": [0, 0], "opacity": [0,1], "duration": 600, "delay":100, "staggervalue": 150, "easing": "easeOutQuad" }'>
                <span class="fs-26 xs-fs-24 alt-font fw-600 text-dark-gray mb-20px d-block">Crear cuenta</span>
                <form action="" method="post">
                    {% csrf_token %}
                    {% if form.errors %}
                        <p class="alert alert-danger">
                            {% for key, value in form.errors.items  %}
                                {{value.0}}
                            {% endfor %}
                        </p>
                    {% endif %}
                    <div class="row gx-3">
                        <div class="col">
                            <label class="text-dark-gray mb-10px fw-500" for="namef">
                                {{form.first_name.label}}
                            </label>
                            {{form.first_name}}
                        </div>
                        <div class="col">
                            <label class="text-dark-gray mb-10px fw-500" for="namel">{{form.last_name.label}}</label>
                            {{form.last_name}}
                        </div>
                    </div>
                    <div class="row gx-3">
                        <div class="col">
                            <label class="text-dark-gray mb-10px fw-500" for="emailadd">{{form.email.label}}</label>
                            {{form.email}}
                        </div>
                    </div>
                    <div class="row gx-3">
                        <div class="col">
                            <label class="text-dark-gray mb-10px fw-500" for="phone_prefix">
                                {{form.phone_prefix.label}}
                            </label>
                            <select class="mb-20px bg-very-light-gray form-select" name="phone_prefix" id="id_phone_prefix" aria-label="Country code">
                                <option value="57" selected>🇨🇴 +57</option>
                                <option value="1">🇺🇸 +1</option>
                            </select>
                        </div>
                        <div class="col">
                            <label class="text-dark-gray mb-10px fw-500" for="namel">{{form.phone_number.label}}</label>
                            {{form.phone_number}}
                        </div>
                    </div>
                <div class="position-relative">
                    <label class="text-dark-gray mb-10px fw-500" for="checkstrength">{{form.password.label}}</label>
                    {{form.password}}
                </div>
                <div class="position-relative">
                    <label class="text-dark-gray mb-10px fw-500" for="passwd">{{form.password_confirmation.label}}</label>
                    {{form.password_confirmation}}
                    <button class="btn btn-medium btn-round-edge btn-base-color btn-box-shadow w-100" type="submit">Registrarme</button>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- end section -->
{% endblock %}

fpt/templates/users/signup.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block title %}Futsal para todos{% endblock %}
{% block content %}
{% endblock %}

fpt/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  {{ user.username }}
{% endblock title %}
{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal"
        method="post"
        action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock content %}